In [6]:
import numpy as np
import scipy.linalg as la

In [7]:
A = np.array([[1,2],[-1,3]])
print(A)

[[ 1  2]
 [-1  3]]


In [8]:
results = la.eig(A) #  by using methord

In [9]:
print(results[0])

[2.+1.j 2.-1.j]


In [11]:
#Example 2:
B = np.array([[3,6,8],[0,0,6],[0,0,2]])
print(B)



[[3 6 8]
 [0 0 6]
 [0 0 2]]


In [13]:
results = la.eig(B)
print(results[0])
             

[3.+0.j 0.+0.j 2.+0.j]


In [21]:
print(results)

(array([3.+0.j, 0.+0.j, 2.+0.j]), array([[ 1.        , -0.89442719, -0.99268461],
       [ 0.        ,  0.4472136 ,  0.11454053],
       [ 0.        ,  0.        ,  0.03818018]]))


In [24]:
# importing numpy library 
import numpy as np 
  
# create numpy 2d-array 
m = np.array([[1, 2], 
              [2, 3]]) 
  
print("Printing the Original square array:\n", 
      m) 
  
# finding eigenvalues and eigenvectors 
w, v = np.linalg.eig(m) 
  
# printing eigen values 
print("Printing the Eigen values of the given square array:\n", 
      w) 
  
# printing eigen vectors 
print("Printing Right eigenvectors of the given square array:\n",
      v)

Printing the Original square array:
 [[1 2]
 [2 3]]
Printing the Eigen values of the given square array:
 [-0.23606798  4.23606798]
Printing Right eigenvectors of the given square array:
 [[-0.85065081 -0.52573111]
 [ 0.52573111 -0.85065081]]


In [25]:
import numpy as np 
  
# create numpy 2d-array 
m = np.array([[1, 2, 3], 
              [2, 3, 4], 
              [4, 5, 6]]) 
  
print("Printing the Original square array:\n", 
      m) 
  
# finding eigenvalues and eigenvectors 
w, v = np.linalg.eig(m) 
  
# printing eigen values 
print("Printing the Eigen values of the given square array:\n", 
      w) 
  
# printing eigen vectors 
print("Printing Right eigenvectors of the given square array:\n", 
      v) 

Printing the Original square array:
 [[1 2 3]
 [2 3 4]
 [4 5 6]]
Printing the Eigen values of the given square array:
 [ 1.08309519e+01 -8.30951895e-01  1.01486082e-16]
Printing Right eigenvectors of the given square array:
 [[ 0.34416959  0.72770285  0.40824829]
 [ 0.49532111  0.27580256 -0.81649658]
 [ 0.79762415 -0.62799801  0.40824829]]
