In [2]:
import numpy as np


In [6]:
array=np.array([1,2,3,4,5])

print(array)

[1 2 3 4 5]


In [7]:
print(type(array))

<class 'numpy.ndarray'>


In [8]:
#One dimention Array
array=np.array([1,2,3,4,5,"aizazkhan","afridi"])

print(array)


['1' '2' '3' '4' '5' 'aizazkhan' 'afridi']


In [9]:
array.ndim

1

In [14]:
a = np.array(42)
b = np.array([1, 2, 3, 4, 5])
c = np.array([[1, 2, 3], [4, 5, 6]])
d = np.array([[[[1,2,3,4,5],[5,6,7,8,9],[1,2,3,4,5,6],[5,4,3,2,1],[2,3,4,4,5,]]]])

print(a.ndim)
print(b.ndim)
print(c.ndim)
print(d.ndim)

0
1
2
3


In [15]:

arr = np.array([1, 2, 3, 4], ndmin=5)

print(arr)
print('number of dimensions :', arr.ndim)

[[[[[1 2 3 4]]]]]
number of dimensions : 5


# Access Array Elements

In [21]:
arr = np.array([1, 2, 3, 4])

print(arr[0])

1


In [25]:
print(arr[2] + arr[3])

7


In [26]:
arr = np.array([[1,2,3,4,5], [6,7,8,9,10]])

print('2nd element on 1st dim: ', arr[0, 1])

2nd element on 1st dim:  2


In [29]:
print(arr[1])
print(arr[1,3])

[ 6  7  8  9 10]
9


# Access the thrid dimention in numpy

In [33]:
arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

print(arr[0, 1, 2])


6


In [35]:
arr = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr[1:5])

[2 3 4 5]


In [36]:
print(arr[4:])

[5 6 7]


In [37]:
print(arr[:4])

[1 2 3 4]


In [38]:
print(arr[-3:-1])

[5 6]


# STEP

In [39]:
print(arr[1:5:2])

[2 4]


In [40]:
print(arr[::2])

[1 3 5 7]


In [44]:
arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])

print(arr[1,1:4])

[7 8 9]


# Checking the Data Type of an Array

 i - integer
b - boolean
u - unsigned integer
f - float
c - complex float
m - timedelta
M - datetime
O - object
S - string

In [45]:

arr = np.array([1, 2, 3, 4])

print(arr.dtype)

int32


In [46]:
arr = np.array(['apple', 'banana', 'cherry'])

print(arr.dtype)

<U6


In [47]:
#converted integer to string
arr = np.array([1, 2, 3, 4], dtype='S')

print(arr)
print(arr.dtype)

[b'1' b'2' b'3' b'4']
|S1


# Converting Data Type on Existing Arrays

In [48]:
arr = np.array([1.1, 2.1, 3.1])

newarr = arr.astype('i')

print(newarr)
print(newarr.dtype)

[1 2 3]
int32


In [49]:
newarr = arr.astype(int)

print(newarr)
print(newarr.dtype)

[1 2 3]
int32


In [50]:
newarr = arr.astype(bool)

print(newarr)
print(newarr.dtype)

[ True  True  True]
bool


# NumPy Array Iteration
NumPy provides an iterator object, i.e.,
nditer which can be used to iterate over the given array using python standard Iterator interface.

In [53]:
a = np.array([[1,2,3,4],[2,4,5,6],[10,20,39,3]])  
print("Printing array:")  
print(a);  
print("Iterating over the array:")  
for x in np.nditer(a):  
    print(x,end=' ') 

Printing array:
[[ 1  2  3  4]
 [ 2  4  5  6]
 [10 20 39  3]]
Iterating over the array:
1 2 3 4 2 4 5 6 10 20 39 3 

In [60]:
a = np.array([[1,2,3,4],[2,4,5,6],[10,20,39,3]])  
print("Printing the array:")  
print(a)  
print("Printing the transpose of the array:")  
at = a.T  
print(at)  
  
#this will be same as previous   
for x in np.nditer(at):    
    print(x,end=' ')  
    

Printing the array:
[[ 1  2  3  4]
 [ 2  4  5  6]
 [10 20 39  3]]
Printing the transpose of the array:
[[ 1  2 10]
 [ 2  4 20]
 [ 3  5 39]
 [ 4  6  3]]
1 2 3 4 2 4 5 6 10 20 39 3 

In [65]:
array4 = np.array([[1,2,3,4],[2,4,5,6],[10,20,39,3]])  
new= 3*array4[2]
update=array4[2]=new
print(array4)



[[  1   2   3   4]
 [  2   4   5   6]
 [ 30  60 117   9]]


# NumPy String Functions

In [66]:
print("Capitalizing the string using capitalize()...")  
print(np.char.capitalize("welcome to javatpoint"))  

Capitalizing the string using capitalize()...
Welcome to javatpoint


In [68]:
print(np.char.lower("WELCOME TO JAVATPOINT"))  

welcome to javatpoint


In [67]:
print("Converting string into title cased version...")  
print(np.char.title("welcome to javatpoint"))  

Converting string into title cased version...
Welcome To Javatpoint


In [69]:
print("Splitting the String word by word..")  
print(np.char.split("Welcome To Javatpoint"),sep = " ")  

Splitting the String word by word..
['Welcome', 'To', 'Javatpoint']


# Operation in Numpy

In [29]:
array1=np.array([[1,2,3,4,5],[2,3,4,5,6]])
array2=np.array([[1,2,6,3,2],[5,6,7,8,7]])
print(array1)


[[1 2 3 4 5]
 [2 3 4 5 6]]


In [30]:
print(array2)

[[1 2 6 3 2]
 [5 6 7 8 7]]


In [31]:
sum_array =array1+array2
print(sum_array)

[[ 2  4  9  7  7]
 [ 7  9 11 13 13]]


In [32]:
np.add(array1,array2)

array([[ 2,  4,  9,  7,  7],
       [ 7,  9, 11, 13, 13]])

In [33]:
subtract=array1-array2
print(subtract)

[[ 0  0 -3  1  3]
 [-3 -3 -3 -3 -1]]


In [34]:
multiplay= array1*array2
print(multiplay)

[[ 1  4 18 12 10]
 [10 18 28 40 42]]


In [42]:
array1=np.array([[1,2,3,4,5],[3,4,5,6,6],[1,2,3,4,5]])
array2=np.array([[1,2,3,4,5],[3,4,5,6,6],[1,2,3,4,5]])


In [43]:
array1

array([[1, 2, 3, 4, 5],
       [3, 4, 5, 6, 6],
       [1, 2, 3, 4, 5]])

In [44]:
array2

array([[1, 2, 3, 4, 5],
       [3, 4, 5, 6, 6],
       [1, 2, 3, 4, 5]])

In [45]:
array1.max()

6

In [46]:
array1.argmax()

8

In [47]:
# find maximuj for columns wise

array1.max( axis =0)

array([3, 4, 5, 6, 6])

In [49]:
# find maximuj for columns wise
array2.max( axis =1)

array([5, 6, 5])

In [50]:
array1.min()

1

In [52]:
array1.argmin()

0

In [53]:
array1.min( axis =0)

array([1, 2, 3, 4, 5])

In [54]:
# find maximuj for columns wise
array2.min( axis =1)

array([1, 3, 1])

In [60]:
array2

array([[1, 2, 3, 4, 5],
       [3, 4, 5, 6, 6],
       [1, 2, 3, 4, 5]])

In [64]:
# sum columns value 

array2.sum( axis=0)

array([ 5,  8, 11, 14, 16])

In [70]:
# sum first rows
col=array2[0]
col.sum()

15

In [61]:
# sum rows in values 

array2.sum( axis=1)

array([15, 24, 15])

# mean median mode in numpy